print("Welcome to the Band Name Generator")
name_of_city = input("Whitch city did you grow up in? \n")
name_of_pets = input("What's your pet's name?\n")
print("the band name could be",name_of_city, name_of_pets)
print("Thaks for use my app")